#Environment Vars for feedScraper

TWITTER_HANDLE = 'ENTERTWITTERHANDLEHERE'
TWITTER_CONSUMER_KEY = 'ENTERCONSUMERKEY';
TWITTER_CONSUMER_SECRET = 'ENTERCONSUMERSECRET'
TWITTER_ACCESS_TOKEN_KEY = 'ENTERACCESSTOKENKEY'
TWITTER_ACCESS_TOKEN_SECRET = 'INSERTACCESSTOKENSECRET'
